config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :messages do
    resources :comments
  end

  root 'messages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :text, presence: true

  belongs_to :user
  belongs_to :message

end

app/models/message.rb
class Message < ApplicationRecord

  validates :text, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy

end

app/models/text_alert.rb
require 'twilio-ruby'

class TextAlert

  attr_reader :message_user, :message_text, :twilio_sid, :twilio_token, :twilio_number

  def initialize(message_user, message_text)
    @message_user = message_user
    @message_text = message_text
    @twilio_sid = ENV['twilio_sid']
    @twilio_token = ENV['twilio_token']
    @twilio_number = ENV['twilio_number']
  end

  def send_texts
    client = Twilio::REST::Client.new(twilio_sid, twilio_token)
    # User.where.not(id: message_user.id).pluck(:mobile).each do |mobile|
    User.pluck(:mobile).each do |mobile|
      client.api.account.messages.create(
        from: twilio_number,
        to: mobile,
        body: text_content
      )
    end
  end

  def text_content
    "#{message_user.email} posted a new message on we_three: #{message_text}\nto reply go to https://we-three.herokuapp.com"
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :messages, dependent: :destroy
  has_many :comments, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @message = Message.find(params[:message_id])
    @comment = @message.comments.new(comment_params)
    @comment.user = current_user
    @comment.time = Time.now
    if @comment.save
      redirect_to message_path(@message)
    end
  end

  def edit
    @message = Message.find(params[:message_id])
    @comment = @message.comments.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to message_path(@comment.message)
    else
      render 'edit'
    end
  end

  def destroy
    @message = Message.find(params[:message_id])
    @comment = @message.comments.find(params[:id])
    @comment.destroy
    redirect_to message_path(@message)
  end

  def comment_params
    params.require(:comment).permit(:text)
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
    @message = Message.new
  end

  def edit
    @message = Message.find(params[:id])
  end

  def show
    @message = Message.find(params[:id])
  end

  def create
    @message = Message.new(message_params)
    @message.user = current_user
    @message.time = Time.now
    if @message.save
      # MessageMailer.notification_email(@message.user.email, @message).deliver_now
      TextAlert.new(current_user, @message.text).send_texts
      redirect_to messages_path
    else
      @messages = Message.all
      render 'index'
    end
  end

  def update
    @message = Message.find(params[:id])
    if @message.update(message_params)
      redirect_to messages_path
    else
      render 'edit'
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to messages_path
  end

  def message_params
    params.require(:message).permit(:text)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:mobile, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:mobile, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/edit.html.erb
<%= form_for [@message, @comment] do |f| %>
  <p><%= f.text_area :text %></p>
  <p><%= f.submit 'comment', :class => 'comment-button' %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeThree</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Artifika" rel="stylesheet">
  </head>

  <body>

    <p class='we-three'> we three </p>

    <% if notice %>
      <p><%= notice %></p>
    <% end %>
    <% if alert %>
      <p><%= alert %></p>
    <% end %>

    <% if user_signed_in? %>
      <p>logged in as <%= current_user.email %> |
      <%= link_to "log out", destroy_user_session_path, method: :delete %> |
      <%= link_to 'edit account', edit_user_registration_path(current_user) %></p>
    <% else %>
      <p><%= link_to "sign up", new_user_registration_path %> |
      <%= link_to "log in", new_user_session_path %></p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>

  <% if @message.errors.any? %>
    <% @message.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>

  <p><%= f.text_area :text %></p>
  <p><%= f.submit 'send', :class => 'message-button' %></p>

<% end %>

app/views/messages/edit.html.erb
<%= render 'form' %>

<%= link_to 'back', messages_path %>

app/views/messages/index.html.erb
<% if current_user %>
  <%= render 'form' %>
<% end %>

<% @messages.reverse.each do |message| %>

    <div class='message-elements'>
      <p><%= message.user.email %>: </p>
        <p class='message-text'><%= message.text %></p>
        <p><%= message.time.strftime('%A at %H:%M') %> |
        <%= link_to "comments(#{message.comments.count})", message_path(message.id) %> |
      <% if current_user == message.user %>
        <%= link_to 'edit', edit_message_path(message) %> |
        <%= link_to 'delete', message_path(message), method: :delete%></p>
      <% end %>
    </div></br>

<% end %>

app/views/messages/show.html.erb
<p><%= @message.user.email %> wrote
<span class='big-message-text'>'<%= @message.text %>'</span>
on <%= @message.time.strftime('%A at %H:%M')%></p>

<p>comments on this message:</p>

<% @message.comments.each do |comment| %>

  <div class='message-elements'>
    <p><%= comment.user.email %>:</p>
    <p class='comment-text'><%= comment.text %></p>
    <p><%= comment.time.strftime('%A at %H:%M') %> |
    <% if current_user == comment.user %>
      <%= link_to 'delete', [comment.message, comment], method: :delete %> |
      <%= link_to 'edit', edit_message_comment_path(comment.message, comment) %></p>
    <% end %>
  </div></br>

<% end %>

<% if current_user %>
  <%= form_for([@message, @message.comments.build]) do |f| %>
    <p><%= f.text_area :text %></p>
    <p><%= f.submit 'comment', :class => 'comment-button' %></p>
  <% end %>
<% end %>

<p><%= link_to 'all messages', messages_path %></p>